"""
sql/write_models.py — typed models for structured write actions.

Design decisions
-----------------
* The LLM NEVER outputs raw SQL for write operations. It outputs JSON
  matching one of these Pydantic models. This is the core safety
  guarantee of the write pipeline: a structured action can be fully
  validated (table whitelist, column whitelist, type checks) BEFORE any
  SQL string is built, which is impossible to do reliably on raw SQL
  text generated by an LLM.
* InsertAction / UpdateAction are kept separate (rather than one big
  "WriteAction" with optional fields) so each has its own required
  fields and its own clean validation surface.
* WriteAction is a discriminated union on the `action` field, so
  `parse_write_action()` can deserialize whichever the LLM produced.
* Pydantic v2 style (matches the rest of the codebase's typing-first
  style) — `model_config`, `Field`, full type hints.
"""
from __future__ import annotations

from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field, TypeAdapter, field_validator

# ---------------------------------------------------------------------------
# Scalar value type accepted in write payloads.
# Kept intentionally narrow — no nested dict/list values, no raw SQL
# expressions. Anything else must be rejected by validation.
# ---------------------------------------------------------------------------
WriteValue = Union[str, int, float, bool, None]


class InsertAction(BaseModel):
    """Structured representation of a single-row INSERT."""

    model_config = {"extra": "forbid"}  # reject unknown JSON fields outright

    action: Literal["INSERT"] = "INSERT"
    table: str = Field(..., min_length=1, description="Target table name, e.g. F_ARTICLE")
    values: dict[str, WriteValue] = Field(
        ..., min_length=1, description="Column → value pairs to insert"
    )

    @field_validator("table")
    @classmethod
    def _uppercase_table(cls, v: str) -> str:
        return v.strip().upper()

    @field_validator("values")
    @classmethod
    def _uppercase_value_keys(cls, v: dict[str, WriteValue]) -> dict[str, WriteValue]:
        return {k.strip().upper(): val for k, val in v.items()}


class UpdateAction(BaseModel):
    """Structured representation of a single-table UPDATE with a WHERE clause."""

    model_config = {"extra": "forbid"}

    action: Literal["UPDATE"] = "UPDATE"
    table: str = Field(..., min_length=1, description="Target table name, e.g. F_ARTSTOCK")
    where: dict[str, WriteValue] = Field(
        ..., min_length=1, description="Column → value pairs identifying the row(s) to update"
    )
    values: dict[str, WriteValue] = Field(
        ..., min_length=1, description="Column → new value pairs to set"
    )

    @field_validator("table")
    @classmethod
    def _uppercase_table(cls, v: str) -> str:
        return v.strip().upper()

    @field_validator("where", "values")
    @classmethod
    def _uppercase_keys(cls, v: dict[str, WriteValue]) -> dict[str, WriteValue]:
        return {k.strip().upper(): val for k, val in v.items()}


# Discriminated union — parse_write_action() picks the right model based on
# the "action" field in the LLM's JSON output.
WriteAction = Annotated[Union[InsertAction, UpdateAction], Field(discriminator="action")]

# TypeAdapter lets us validate raw dict/JSON straight into the discriminated
# union without needing a wrapper BaseModel (Pydantic v2 idiomatic approach).
_write_action_adapter: TypeAdapter[WriteAction] = TypeAdapter(WriteAction)


def parse_write_action(raw: dict) -> WriteAction:
    """
    Parse a raw dict (already JSON-decoded from the LLM output) into a
    concrete InsertAction or UpdateAction, based on its "action" field.

    Raises pydantic.ValidationError if the shape is invalid — callers
    (core/write_agent.py) catch this and surface it as a validation error
    rather than letting it propagate as an unhandled exception.
    """
    return _write_action_adapter.validate_python(raw)
